export const COMPETITIONS = {
  laliga:     { key: 'laliga',     label: '🇪🇸 LaLiga' },
  premier:    { key: 'premier',    label: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 Premier League' },
  bundesliga: { key: 'bundesliga', label: '🇩🇪 Bundesliga' },
  seriea:     { key: 'seriea',     label: '🇮🇹 Serie A' },
  ligue1:     { key: 'ligue1',     label: '🇫🇷 Ligue 1' },
  champions:  { key: 'champions',  label: '⭐ Champions League' },
};

export const FORMATIONS = {
  "4-3-3": [
    {pos:"POR",r:1,c:3},
    {pos:"DEF",r:2,c:1},{pos:"DEF",r:2,c:2},{pos:"DEF",r:2,c:4},{pos:"DEF",r:2,c:5},
    {pos:"MED",r:3,c:2},{pos:"MED",r:3,c:3},{pos:"MED",r:3,c:4},
    {pos:"DEL",r:4,c:1},{pos:"DEL",r:4,c:3},{pos:"DEL",r:4,c:5},
  ],
  "4-4-2": [
    {pos:"POR",r:1,c:3},
    {pos:"DEF",r:2,c:1},{pos:"DEF",r:2,c:2},{pos:"DEF",r:2,c:4},{pos:"DEF",r:2,c:5},
    {pos:"MED",r:3,c:1},{pos:"MED",r:3,c:2},{pos:"MED",r:3,c:4},{pos:"MED",r:3,c:5},
    {pos:"DEL",r:4,c:2},{pos:"DEL",r:4,c:4},
  ],
  "3-5-2": [
    {pos:"POR",r:1,c:3},
    {pos:"DEF",r:2,c:2},{pos:"DEF",r:2,c:3},{pos:"DEF",r:2,c:4},
    {pos:"MED",r:3,c:1},{pos:"MED",r:3,c:2},{pos:"MED",r:3,c:3},{pos:"MED",r:3,c:4},{pos:"MED",r:3,c:5},
    {pos:"DEL",r:4,c:2},{pos:"DEL",r:4,c:4},
  ],
  "4-2-3-1": [
    {pos:"POR",r:1,c:3},
    {pos:"DEF",r:2,c:1},{pos:"DEF",r:2,c:2},{pos:"DEF",r:2,c:4},{pos:"DEF",r:2,c:5},
    {pos:"MED",r:3,c:2},{pos:"MED",r:3,c:4},
    {pos:"MED",r:4,c:1},{pos:"MED",r:4,c:3},{pos:"MED",r:4,c:5},
    {pos:"DEL",r:5,c:3},
  ],
  "4-5-1": [
    {pos:"POR",r:1,c:3},
    {pos:"DEF",r:2,c:1},{pos:"DEF",r:2,c:2},{pos:"DEF",r:2,c:4},{pos:"DEF",r:2,c:5},
    {pos:"MED",r:3,c:1},{pos:"MED",r:3,c:2},{pos:"MED",r:3,c:3},{pos:"MED",r:3,c:4},{pos:"MED",r:3,c:5},
    {pos:"DEL",r:4,c:3},
  ],
  "5-3-2": [
    {pos:"POR",r:1,c:3},
    {pos:"DEF",r:2,c:1},{pos:"DEF",r:2,c:2},{pos:"DEF",r:2,c:3},{pos:"DEF",r:2,c:4},{pos:"DEF",r:2,c:5},
    {pos:"MED",r:3,c:2},{pos:"MED",r:3,c:3},{pos:"MED",r:3,c:4},
    {pos:"DEL",r:4,c:2},{pos:"DEL",r:4,c:4},
  ],
  "3-4-3": [
    {pos:"POR",r:1,c:3},
    {pos:"DEF",r:2,c:2},{pos:"DEF",r:2,c:3},{pos:"DEF",r:2,c:4},
    {pos:"MED",r:3,c:1},{pos:"MED",r:3,c:2},{pos:"MED",r:3,c:4},{pos:"MED",r:3,c:5},
    {pos:"DEL",r:4,c:1},{pos:"DEL",r:4,c:3},{pos:"DEL",r:4,c:5},
  ],
  "5-4-1": [
    {pos:"POR",r:1,c:3},
    {pos:"DEF",r:2,c:1},{pos:"DEF",r:2,c:2},{pos:"DEF",r:2,c:3},{pos:"DEF",r:2,c:4},{pos:"DEF",r:2,c:5},
    {pos:"MED",r:3,c:1},{pos:"MED",r:3,c:2},{pos:"MED",r:3,c:4},{pos:"MED",r:3,c:5},
    {pos:"DEL",r:4,c:3},
  ],
};

export const PLAYERS = [
  // ── LaLiga ────────────────────────────────────────────
  {id:1,  name:"T. Courtois",    team:"Real Madrid",  pos:"POR", val:12, pts:87,  competition:"laliga",     emoji:"🧤"},
  {id:2,  name:"M. Oblak",       team:"Atlético",     pos:"POR", val:11, pts:79,  competition:"laliga",     emoji:"🧤"},
  {id:3,  name:"I. Peña",        team:"Barcelona",    pos:"POR", val: 7, pts:65,  competition:"laliga",     emoji:"🧤"},
  {id:4,  name:"D. Carvajal",    team:"Real Madrid",  pos:"DEF", val:10, pts:74,  competition:"laliga",     emoji:"🛡️"},
  {id:5,  name:"F. Mendy",       team:"Real Madrid",  pos:"DEF", val: 8, pts:68,  competition:"laliga",     emoji:"🛡️"},
  {id:6,  name:"J. Gayà",        team:"Valencia",     pos:"DEF", val: 7, pts:61,  competition:"laliga",     emoji:"🛡️"},
  {id:7,  name:"R. Le Normand",  team:"Atlético",     pos:"DEF", val: 9, pts:70,  competition:"laliga",     emoji:"🛡️"},
  {id:8,  name:"Pedri",          team:"Barcelona",    pos:"MED", val:14, pts:88,  competition:"laliga",     emoji:"⚡"},
  {id:9,  name:"F. Valverde",    team:"Real Madrid",  pos:"MED", val:13, pts:85,  competition:"laliga",     emoji:"⚡"},
  {id:10, name:"T. Kroos",       team:"Real Madrid",  pos:"MED", val:12, pts:82,  competition:"laliga",     emoji:"⚡"},
  {id:11, name:"Gavi",           team:"Barcelona",    pos:"MED", val:11, pts:78,  competition:"laliga",     emoji:"⚡"},
  {id:12, name:"Vinicius Jr",    team:"Real Madrid",  pos:"DEL", val:20, pts:98,  competition:"laliga",     emoji:"🔥"},
  {id:13, name:"R. Lewandowski", team:"Barcelona",    pos:"DEL", val:18, pts:94,  competition:"laliga",     emoji:"🔥"},
  {id:14, name:"Bellingham",     team:"Real Madrid",  pos:"DEL", val:19, pts:96,  competition:"laliga",     emoji:"🔥"},
  {id:15, name:"A. Griezmann",   team:"Atlético",     pos:"DEL", val:15, pts:89,  competition:"laliga",     emoji:"🔥"},
  {id:16, name:"Rodrygo",        team:"Real Madrid",  pos:"DEL", val:14, pts:84,  competition:"laliga",     emoji:"🔥"},
  {id:17, name:"A. Yamal",       team:"Barcelona",    pos:"DEL", val:17, pts:92,  competition:"laliga",     emoji:"🔥"},
  // ── Premier League ────────────────────────────────────
  {id:20, name:"A. Raya",        team:"Arsenal",      pos:"POR", val:10, pts:80,  competition:"premier",    emoji:"🧤"},
  {id:21, name:"E. Martínez",    team:"Aston Villa",  pos:"POR", val:11, pts:82,  competition:"premier",    emoji:"🧤"},
  {id:22, name:"A. Arnold",      team:"Liverpool",    pos:"DEF", val:13, pts:86,  competition:"premier",    emoji:"🛡️"},
  {id:23, name:"K. Walker",      team:"Man City",     pos:"DEF", val:10, pts:74,  competition:"premier",    emoji:"🛡️"},
  {id:24, name:"B. White",       team:"Arsenal",      pos:"DEF", val: 9, pts:72,  competition:"premier",    emoji:"🛡️"},
  {id:25, name:"M. Salah",       team:"Liverpool",    pos:"DEL", val:20, pts:99,  competition:"premier",    emoji:"🔥"},
  {id:26, name:"E. Haaland",     team:"Man City",     pos:"DEL", val:22, pts:101, competition:"premier",    emoji:"🔥"},
  {id:27, name:"B. Saka",        team:"Arsenal",      pos:"DEL", val:18, pts:93,  competition:"premier",    emoji:"🔥"},
  {id:28, name:"P. Foden",       team:"Man City",     pos:"MED", val:16, pts:90,  competition:"premier",    emoji:"⚡"},
  {id:29, name:"M. De Bruyne",   team:"Man City",     pos:"MED", val:17, pts:88,  competition:"premier",    emoji:"⚡"},
  {id:30, name:"D. Rice",        team:"Arsenal",      pos:"MED", val:14, pts:83,  competition:"premier",    emoji:"⚡"},
  {id:31, name:"C. Palmer",      team:"Chelsea",      pos:"MED", val:16, pts:89,  competition:"premier",    emoji:"⚡"},
  {id:32, name:"O. Watkins",     team:"Aston Villa",  pos:"DEL", val:14, pts:85,  competition:"premier",    emoji:"🔥"},
  {id:33, name:"Son H-M",        team:"Tottenham",    pos:"DEL", val:14, pts:82,  competition:"premier",    emoji:"🔥"},
  {id:34, name:"T. Alexander-A",team:"Liverpool",    pos:"DEF", val:11, pts:76,  competition:"premier",    emoji:"🛡️"},
  // ── Champions League ──────────────────────────────────
  {id:40, name:"G. Donnarumma",  team:"PSG",          pos:"POR", val:12, pts:84,  competition:"champions",  emoji:"🧤"},
  {id:41, name:"M. Neuer",       team:"Bayern",       pos:"POR", val:10, pts:75,  competition:"champions",  emoji:"🧤"},
  {id:42, name:"T. Hernández",   team:"Bayern",       pos:"DEF", val:11, pts:78,  competition:"champions",  emoji:"🛡️"},
  {id:43, name:"R. Hakimi",      team:"PSG",          pos:"DEF", val:12, pts:80,  competition:"champions",  emoji:"🛡️"},
  {id:44, name:"A. Davies",      team:"Bayern",       pos:"DEF", val:10, pts:74,  competition:"champions",  emoji:"🛡️"},
  {id:45, name:"K. Mbappé",      team:"Real Madrid",  pos:"DEL", val:22, pts:97,  competition:"champions",  emoji:"🔥"},
  {id:46, name:"H. Kane",        team:"Bayern",       pos:"DEL", val:19, pts:95,  competition:"champions",  emoji:"🔥"},
  {id:47, name:"V. Osimhen",     team:"Napoli",       pos:"DEL", val:16, pts:88,  competition:"champions",  emoji:"🔥"},
  {id:48, name:"J. Musiala",     team:"Bayern",       pos:"MED", val:15, pts:86,  competition:"champions",  emoji:"⚡"},
  {id:49, name:"N. Barella",     team:"Inter",        pos:"MED", val:13, pts:82,  competition:"champions",  emoji:"⚡"},
  {id:50, name:"Vítinha",        team:"PSG",          pos:"MED", val:13, pts:81,  competition:"champions",  emoji:"⚡"},
  {id:51, name:"R. Dias",        team:"Man City",     pos:"DEF", val:12, pts:79,  competition:"champions",  emoji:"🛡️"},
  // ── Bundesliga ────────────────────────────────────────
  {id:60, name:"O. Baumann",     team:"B. München",   pos:"POR", val: 8, pts:71,  competition:"bundesliga", emoji:"🧤"},
  {id:61, name:"G. ter Stegen",  team:"Barcelona",    pos:"POR", val:10, pts:76,  competition:"bundesliga", emoji:"🧤"},
  {id:62, name:"J. Kimmich",     team:"B. München",   pos:"DEF", val:13, pts:84,  competition:"bundesliga", emoji:"🛡️"},
  {id:63, name:"D. Raum",        team:"Leipzig",      pos:"DEF", val: 9, pts:69,  competition:"bundesliga", emoji:"🛡️"},
  {id:64, name:"M. Hummels",     team:"Dortmund",     pos:"DEF", val: 8, pts:66,  competition:"bundesliga", emoji:"🛡️"},
  {id:65, name:"L. Goretzka",    team:"B. München",   pos:"MED", val:11, pts:79,  competition:"bundesliga", emoji:"⚡"},
  {id:66, name:"F. Wirtz",       team:"Leverkusen",   pos:"MED", val:18, pts:95,  competition:"bundesliga", emoji:"⚡"},
  {id:67, name:"G. Xhaka",       team:"Leverkusen",   pos:"MED", val:12, pts:80,  competition:"bundesliga", emoji:"⚡"},
  {id:68, name:"S. Gnabry",      team:"B. München",   pos:"DEL", val:13, pts:82,  competition:"bundesliga", emoji:"🔥"},
  {id:69, name:"V. Boniface",    team:"Leverkusen",   pos:"DEL", val:15, pts:87,  competition:"bundesliga", emoji:"🔥"},
  {id:70, name:"H. Füllkrug",    team:"Dortmund",     pos:"DEL", val:12, pts:78,  competition:"bundesliga", emoji:"🔥"},
  {id:71, name:"J. Beier",       team:"Hoffenheim",   pos:"DEL", val:11, pts:74,  competition:"bundesliga", emoji:"🔥"},
  {id:72, name:"A. Schlotterbeck",team:"Dortmund",   pos:"DEF", val: 9, pts:70,  competition:"bundesliga", emoji:"🛡️"},
  // ── Serie A ───────────────────────────────────────────
  {id:80, name:"G. Donnarumma",  team:"PSG/Italia",   pos:"POR", val:11, pts:78,  competition:"seriea",     emoji:"🧤"},
  {id:81, name:"M. Maignan",     team:"AC Milan",     pos:"POR", val:10, pts:75,  competition:"seriea",     emoji:"🧤"},
  {id:82, name:"G. Di Lorenzo",  team:"Napoli",       pos:"DEF", val:10, pts:73,  competition:"seriea",     emoji:"🛡️"},
  {id:83, name:"A. Bastoni",     team:"Inter",        pos:"DEF", val:11, pts:77,  competition:"seriea",     emoji:"🛡️"},
  {id:84, name:"F. Acerbi",      team:"Inter",        pos:"DEF", val: 8, pts:65,  competition:"seriea",     emoji:"🛡️"},
  {id:85, name:"N. Barella",     team:"Inter",        pos:"MED", val:14, pts:83,  competition:"seriea",     emoji:"⚡"},
  {id:86, name:"H. Calhanoglu",  team:"Inter",        pos:"MED", val:12, pts:80,  competition:"seriea",     emoji:"⚡"},
  {id:87, name:"F. Chiesa",      team:"Juventus",     pos:"DEL", val:13, pts:79,  competition:"seriea",     emoji:"🔥"},
  {id:88, name:"L. Martinez",    team:"Inter",        pos:"DEL", val:17, pts:91,  competition:"seriea",     emoji:"🔥"},
  {id:89, name:"V. Osimhen",     team:"Napoli",       pos:"DEL", val:18, pts:93,  competition:"seriea",     emoji:"🔥"},
  {id:90, name:"R. Leão",        team:"AC Milan",     pos:"DEL", val:16, pts:88,  competition:"seriea",     emoji:"🔥"},
  {id:91, name:"P. Dybala",      team:"Roma",         pos:"DEL", val:14, pts:82,  competition:"seriea",     emoji:"🔥"},
  {id:92, name:"G. Mancini",     team:"Roma",         pos:"DEF", val: 8, pts:64,  competition:"seriea",     emoji:"🛡️"},
  {id:93, name:"S. Tonali",      team:"AC Milan",     pos:"MED", val:11, pts:76,  competition:"seriea",     emoji:"⚡"},
  // ── Ligue 1 ───────────────────────────────────────────
  {id:100,name:"G. Donnarumma",  team:"PSG",          pos:"POR", val:12, pts:81,  competition:"ligue1",     emoji:"🧤"},
  {id:101,name:"B. Samba",       team:"Lens",         pos:"POR", val: 8, pts:70,  competition:"ligue1",     emoji:"🧤"},
  {id:102,name:"N. Mukiele",     team:"PSG",          pos:"DEF", val: 9, pts:68,  competition:"ligue1",     emoji:"🛡️"},
  {id:103,name:"W. Saliba",      team:"Arsenal/Fr",   pos:"DEF", val:11, pts:76,  competition:"ligue1",     emoji:"🛡️"},
  {id:104,name:"T. Hernández",   team:"AC Milan/Fr",  pos:"DEF", val:11, pts:74,  competition:"ligue1",     emoji:"🛡️"},
  {id:105,name:"Vítinha",        team:"PSG",          pos:"MED", val:13, pts:80,  competition:"ligue1",     emoji:"⚡"},
  {id:106,name:"W. Fofana",      team:"PSG",          pos:"MED", val:10, pts:72,  competition:"ligue1",     emoji:"⚡"},
  {id:107,name:"K. Mbappé",      team:"PSG/France",   pos:"DEL", val:22, pts:99,  competition:"ligue1",     emoji:"🔥"},
  {id:108,name:"O. Dembélé",     team:"PSG",          pos:"DEL", val:16, pts:87,  competition:"ligue1",     emoji:"🔥"},
  {id:109,name:"M. Thuram",      team:"Inter/Fr",     pos:"DEL", val:14, pts:83,  competition:"ligue1",     emoji:"🔥"},
  {id:110,name:"T. Weah",        team:"Juventus/Fr",  pos:"DEL", val:10, pts:68,  competition:"ligue1",     emoji:"🔥"},
  {id:111,name:"B. Koné",        team:"Monaco",       pos:"DEF", val: 9, pts:67,  competition:"ligue1",     emoji:"🛡️"},
  {id:112,name:"W. Khazri",      team:"Montpellier",  pos:"MED", val: 8, pts:63,  competition:"ligue1",     emoji:"⚡"},

  // ── La Liga — plantillas completas (temporada 2025-26) ────────────────────
  // Barcelona
  {id:200,name:"Joan García",            team:"Barcelona",      pos:"POR",val: 9,pts:72,competition:"laliga",emoji:"🧤"},
  {id:201,name:"Wojciech Szczesny",      team:"Barcelona",      pos:"POR",val: 6,pts:60,competition:"laliga",emoji:"🧤"},
  {id:202,name:"João Cancelo",           team:"Barcelona",      pos:"DEF",val: 9,pts:68,competition:"laliga",emoji:"🛡️"},
  {id:203,name:"Alejandro Balde",        team:"Barcelona",      pos:"DEF",val:10,pts:70,competition:"laliga",emoji:"🛡️"},
  {id:204,name:"Ronald Araújo",          team:"Barcelona",      pos:"DEF",val:12,pts:76,competition:"laliga",emoji:"🛡️"},
  {id:205,name:"Pau Cubarsí",            team:"Barcelona",      pos:"DEF",val:11,pts:74,competition:"laliga",emoji:"🛡️"},
  {id:206,name:"Jules Koundé",           team:"Barcelona",      pos:"DEF",val:12,pts:78,competition:"laliga",emoji:"🛡️"},
  {id:207,name:"Andreas Christensen",    team:"Barcelona",      pos:"DEF",val: 9,pts:68,competition:"laliga",emoji:"🛡️"},
  {id:208,name:"Gerard Martín",          team:"Barcelona",      pos:"DEF",val: 6,pts:58,competition:"laliga",emoji:"🛡️"},
  {id:209,name:"Eric García",            team:"Barcelona",      pos:"DEF",val: 6,pts:55,competition:"laliga",emoji:"🛡️"},
  {id:210,name:"Gavi",                   team:"Barcelona",      pos:"MED",val:12,pts:80,competition:"laliga",emoji:"⚡"},
  {id:211,name:"Pedri",                  team:"Barcelona",      pos:"MED",val:15,pts:87,competition:"laliga",emoji:"⚡"},
  {id:212,name:"Fermín López",           team:"Barcelona",      pos:"MED",val: 9,pts:70,competition:"laliga",emoji:"⚡"},
  {id:213,name:"Marc Casadó",            team:"Barcelona",      pos:"MED",val: 7,pts:62,competition:"laliga",emoji:"⚡"},
  {id:214,name:"Dani Olmo",              team:"Barcelona",      pos:"MED",val:13,pts:84,competition:"laliga",emoji:"⚡"},
  {id:215,name:"Frenkie de Jong",        team:"Barcelona",      pos:"MED",val:13,pts:82,competition:"laliga",emoji:"⚡"},
  {id:216,name:"Marc Bernal",            team:"Barcelona",      pos:"MED",val: 7,pts:60,competition:"laliga",emoji:"⚡"},
  {id:217,name:"Lamine Yamal",           team:"Barcelona",      pos:"DEL",val:18,pts:92,competition:"laliga",emoji:"🔥"},
  {id:218,name:"R. Lewandowski",         team:"Barcelona",      pos:"DEL",val:16,pts:88,competition:"laliga",emoji:"🔥"},
  {id:219,name:"Raphinha",               team:"Barcelona",      pos:"DEL",val:14,pts:85,competition:"laliga",emoji:"🔥"},
  {id:220,name:"M. Rashford",            team:"Barcelona",      pos:"DEL",val:12,pts:75,competition:"laliga",emoji:"🔥"},
  {id:221,name:"Ferran Torres",          team:"Barcelona",      pos:"DEL",val: 8,pts:65,competition:"laliga",emoji:"🔥"},
  // Real Madrid
  {id:222,name:"T. Courtois",            team:"Real Madrid",    pos:"POR",val:12,pts:87,competition:"laliga",emoji:"🧤"},
  {id:223,name:"Andriy Lunin",           team:"Real Madrid",    pos:"POR",val: 8,pts:70,competition:"laliga",emoji:"🧤"},
  {id:224,name:"Dani Carvajal",          team:"Real Madrid",    pos:"DEF",val:10,pts:74,competition:"laliga",emoji:"🛡️"},
  {id:225,name:"Éder Militão",           team:"Real Madrid",    pos:"DEF",val:11,pts:74,competition:"laliga",emoji:"🛡️"},
  {id:226,name:"David Alaba",            team:"Real Madrid",    pos:"DEF",val: 9,pts:65,competition:"laliga",emoji:"🛡️"},
  {id:227,name:"T. Alexander-Arnold",    team:"Real Madrid",    pos:"DEF",val:13,pts:80,competition:"laliga",emoji:"🛡️"},
  {id:228,name:"Raúl Asencio",           team:"Real Madrid",    pos:"DEF",val: 7,pts:62,competition:"laliga",emoji:"🛡️"},
  {id:229,name:"Fran García",            team:"Real Madrid",    pos:"DEF",val: 7,pts:60,competition:"laliga",emoji:"🛡️"},
  {id:230,name:"Antonio Rüdiger",        team:"Real Madrid",    pos:"DEF",val:10,pts:72,competition:"laliga",emoji:"🛡️"},
  {id:231,name:"Ferland Mendy",          team:"Real Madrid",    pos:"DEF",val: 8,pts:68,competition:"laliga",emoji:"🛡️"},
  {id:232,name:"Álvaro Carreras",        team:"Real Madrid",    pos:"DEF",val: 6,pts:55,competition:"laliga",emoji:"🛡️"},
  {id:233,name:"Jude Bellingham",        team:"Real Madrid",    pos:"MED",val:20,pts:96,competition:"laliga",emoji:"⚡"},
  {id:234,name:"E. Camavinga",           team:"Real Madrid",    pos:"MED",val:12,pts:80,competition:"laliga",emoji:"⚡"},
  {id:235,name:"F. Valverde",            team:"Real Madrid",    pos:"MED",val:13,pts:85,competition:"laliga",emoji:"⚡"},
  {id:236,name:"A. Tchouaméni",          team:"Real Madrid",    pos:"MED",val:12,pts:78,competition:"laliga",emoji:"⚡"},
  {id:237,name:"Arda Güler",             team:"Real Madrid",    pos:"MED",val:12,pts:76,competition:"laliga",emoji:"⚡"},
  {id:238,name:"Brahim Díaz",            team:"Real Madrid",    pos:"MED",val: 9,pts:70,competition:"laliga",emoji:"⚡"},
  {id:239,name:"Dani Ceballos",          team:"Real Madrid",    pos:"MED",val: 6,pts:60,competition:"laliga",emoji:"⚡"},
  {id:240,name:"Vinícius Júnior",        team:"Real Madrid",    pos:"DEL",val:20,pts:98,competition:"laliga",emoji:"🔥"},
  {id:241,name:"Kylian Mbappé",          team:"Real Madrid",    pos:"DEL",val:22,pts:97,competition:"laliga",emoji:"🔥"},
  {id:242,name:"Rodrygo",                team:"Real Madrid",    pos:"DEL",val:14,pts:84,competition:"laliga",emoji:"🔥"},
  {id:243,name:"F. Mastantuono",         team:"Real Madrid",    pos:"DEL",val:10,pts:70,competition:"laliga",emoji:"🔥"},
  // Atlético Madrid
  {id:244,name:"Jan Oblak",              team:"Atlético",       pos:"POR",val:12,pts:83,competition:"laliga",emoji:"🧤"},
  {id:245,name:"Juan Musso",             team:"Atlético",       pos:"POR",val: 7,pts:64,competition:"laliga",emoji:"🧤"},
  {id:246,name:"J.Mª Giménez",          team:"Atlético",       pos:"DEF",val: 9,pts:68,competition:"laliga",emoji:"🛡️"},
  {id:247,name:"Matteo Ruggeri",         team:"Atlético",       pos:"DEF",val: 7,pts:60,competition:"laliga",emoji:"🛡️"},
  {id:248,name:"C. Lenglet",             team:"Atlético",       pos:"DEF",val: 6,pts:58,competition:"laliga",emoji:"🛡️"},
  {id:249,name:"Nahuel Molina",          team:"Atlético",       pos:"DEF",val:10,pts:70,competition:"laliga",emoji:"🛡️"},
  {id:250,name:"Dávid Hancko",           team:"Atlético",       pos:"DEF",val: 9,pts:66,competition:"laliga",emoji:"🛡️"},
  {id:251,name:"Marc Pubill",            team:"Atlético",       pos:"DEF",val: 6,pts:58,competition:"laliga",emoji:"🛡️"},
  {id:252,name:"R. Le Normand",          team:"Atlético",       pos:"DEF",val: 9,pts:70,competition:"laliga",emoji:"🛡️"},
  {id:253,name:"Johnny Cardoso",         team:"Atlético",       pos:"MED",val: 7,pts:62,competition:"laliga",emoji:"⚡"},
  {id:254,name:"Koke",                   team:"Atlético",       pos:"MED",val: 8,pts:66,competition:"laliga",emoji:"⚡"},
  {id:255,name:"Pablo Barrios",          team:"Atlético",       pos:"MED",val: 9,pts:72,competition:"laliga",emoji:"⚡"},
  {id:256,name:"Álex Baena",             team:"Atlético",       pos:"MED",val:11,pts:78,competition:"laliga",emoji:"⚡"},
  {id:257,name:"Thiago Almada",          team:"Atlético",       pos:"MED",val: 9,pts:68,competition:"laliga",emoji:"⚡"},
  {id:258,name:"Marcos Llorente",        team:"Atlético",       pos:"MED",val: 9,pts:68,competition:"laliga",emoji:"⚡"},
  {id:259,name:"A. Griezmann",           team:"Atlético",       pos:"DEL",val:15,pts:89,competition:"laliga",emoji:"🔥"},
  {id:260,name:"A. Sørloth",             team:"Atlético",       pos:"DEL",val:10,pts:74,competition:"laliga",emoji:"🔥"},
  {id:261,name:"Julián Álvarez",         team:"Atlético",       pos:"DEL",val:16,pts:87,competition:"laliga",emoji:"🔥"},
  {id:262,name:"A. Lookman",             team:"Atlético",       pos:"DEL",val:14,pts:83,competition:"laliga",emoji:"🔥"},
  {id:263,name:"G. Simeone",             team:"Atlético",       pos:"DEL",val: 8,pts:65,competition:"laliga",emoji:"🔥"},
  // Villarreal
  {id:264,name:"Luiz Júnior",            team:"Villarreal",     pos:"POR",val:10,pts:78,competition:"laliga",emoji:"🧤"},
  {id:265,name:"Diego Conde",            team:"Villarreal",     pos:"POR",val: 5,pts:55,competition:"laliga",emoji:"🧤"},
  {id:266,name:"Logan Costa",            team:"Villarreal",     pos:"DEF",val: 7,pts:60,competition:"laliga",emoji:"🛡️"},
  {id:267,name:"Rafa Marín",             team:"Villarreal",     pos:"DEF",val: 7,pts:60,competition:"laliga",emoji:"🛡️"},
  {id:268,name:"Juan Foyth",             team:"Villarreal",     pos:"DEF",val: 8,pts:65,competition:"laliga",emoji:"🛡️"},
  {id:269,name:"Sergi Cardona",          team:"Villarreal",     pos:"DEF",val: 6,pts:58,competition:"laliga",emoji:"🛡️"},
  {id:270,name:"Alfonso Pedraza",        team:"Villarreal",     pos:"DEF",val: 7,pts:62,competition:"laliga",emoji:"🛡️"},
  {id:271,name:"Dani Parejo",            team:"Villarreal",     pos:"MED",val: 8,pts:70,competition:"laliga",emoji:"⚡"},
  {id:272,name:"Santi Comesaña",         team:"Villarreal",     pos:"MED",val: 6,pts:58,competition:"laliga",emoji:"⚡"},
  {id:273,name:"Thomas Partey",          team:"Villarreal",     pos:"MED",val: 8,pts:65,competition:"laliga",emoji:"⚡"},
  {id:274,name:"Pape Gueye",             team:"Villarreal",     pos:"MED",val: 6,pts:58,competition:"laliga",emoji:"⚡"},
  {id:275,name:"Alberto Moleiro",        team:"Villarreal",     pos:"MED",val: 8,pts:64,competition:"laliga",emoji:"⚡"},
  {id:276,name:"Gerard Moreno",          team:"Villarreal",     pos:"DEL",val:10,pts:72,competition:"laliga",emoji:"🔥"},
  {id:277,name:"G. Mikautadze",          team:"Villarreal",     pos:"DEL",val: 9,pts:68,competition:"laliga",emoji:"🔥"},
  {id:278,name:"Ayoze Pérez",            team:"Villarreal",     pos:"DEL",val: 7,pts:60,competition:"laliga",emoji:"🔥"},
  {id:279,name:"Tajon Buchanan",         team:"Villarreal",     pos:"DEL",val: 7,pts:60,competition:"laliga",emoji:"🔥"},
  // Real Betis
  {id:280,name:"Álvaro Valles",          team:"Real Betis",     pos:"POR",val: 7,pts:65,competition:"laliga",emoji:"🧤"},
  {id:281,name:"Pau López",              team:"Real Betis",     pos:"POR",val: 6,pts:58,competition:"laliga",emoji:"🧤"},
  {id:282,name:"H. Bellerín",            team:"Real Betis",     pos:"DEF",val: 6,pts:58,competition:"laliga",emoji:"🛡️"},
  {id:283,name:"Diego Llorente",         team:"Real Betis",     pos:"DEF",val: 6,pts:56,competition:"laliga",emoji:"🛡️"},
  {id:284,name:"Natan",                  team:"Real Betis",     pos:"DEF",val: 7,pts:60,competition:"laliga",emoji:"🛡️"},
  {id:285,name:"Marc Bartra",            team:"Real Betis",     pos:"DEF",val: 6,pts:56,competition:"laliga",emoji:"🛡️"},
  {id:286,name:"Valentín Gómez",         team:"Real Betis",     pos:"DEF",val: 6,pts:58,competition:"laliga",emoji:"🛡️"},
  {id:287,name:"Junior Firpo",           team:"Real Betis",     pos:"DEF",val: 7,pts:60,competition:"laliga",emoji:"🛡️"},
  {id:288,name:"Pablo Fornals",          team:"Real Betis",     pos:"MED",val: 8,pts:64,competition:"laliga",emoji:"⚡"},
  {id:289,name:"Sofyan Amrabat",         team:"Real Betis",     pos:"MED",val: 8,pts:64,competition:"laliga",emoji:"⚡"},
  {id:290,name:"Álvaro Fidalgo",         team:"Real Betis",     pos:"MED",val: 6,pts:58,competition:"laliga",emoji:"⚡"},
  {id:291,name:"Rodrigo Riquelme",       team:"Real Betis",     pos:"MED",val: 7,pts:62,competition:"laliga",emoji:"⚡"},
  {id:292,name:"Nelson Deossa",          team:"Real Betis",     pos:"MED",val: 6,pts:60,competition:"laliga",emoji:"⚡"},
  {id:293,name:"Giovani Lo Celso",       team:"Real Betis",     pos:"MED",val: 9,pts:70,competition:"laliga",emoji:"⚡"},
  {id:294,name:"Isco",                   team:"Real Betis",     pos:"MED",val: 8,pts:68,competition:"laliga",emoji:"⚡"},
  {id:295,name:"Antony",                 team:"Real Betis",     pos:"DEL",val: 7,pts:60,competition:"laliga",emoji:"🔥"},
  {id:296,name:"Chimy Ávila",            team:"Real Betis",     pos:"DEL",val: 8,pts:66,competition:"laliga",emoji:"🔥"},
  {id:297,name:"Abde Ezzalzouli",        team:"Real Betis",     pos:"DEL",val: 8,pts:64,competition:"laliga",emoji:"🔥"},
  {id:298,name:"Cucho Hernández",        team:"Real Betis",     pos:"DEL",val: 8,pts:65,competition:"laliga",emoji:"🔥"},
  {id:299,name:"Cédric Bakambu",         team:"Real Betis",     pos:"DEL",val: 6,pts:58,competition:"laliga",emoji:"🔥"},
  // Getafe
  {id:300,name:"David Soria",            team:"Getafe",         pos:"POR",val: 7,pts:65,competition:"laliga",emoji:"🧤"},
  {id:301,name:"Jirí Letácek",           team:"Getafe",         pos:"POR",val: 5,pts:55,competition:"laliga",emoji:"🧤"},
  {id:302,name:"Djené",                  team:"Getafe",         pos:"DEF",val: 7,pts:62,competition:"laliga",emoji:"🛡️"},
  {id:303,name:"Domingos Duarte",        team:"Getafe",         pos:"DEF",val: 6,pts:58,competition:"laliga",emoji:"🛡️"},
  {id:304,name:"Kiko Femenía",           team:"Getafe",         pos:"DEF",val: 6,pts:56,competition:"laliga",emoji:"🛡️"},
  {id:305,name:"Diego Rico",             team:"Getafe",         pos:"DEF",val: 5,pts:54,competition:"laliga",emoji:"🛡️"},
  {id:306,name:"Luis Milla",             team:"Getafe",         pos:"MED",val: 6,pts:60,competition:"laliga",emoji:"⚡"},
  {id:307,name:"Mauro Arambarri",        team:"Getafe",         pos:"MED",val: 7,pts:62,competition:"laliga",emoji:"⚡"},
  {id:308,name:"V. Birmancevic",         team:"Getafe",         pos:"MED",val: 6,pts:58,competition:"laliga",emoji:"⚡"},
  {id:309,name:"Borja Mayoral",          team:"Getafe",         pos:"DEL",val: 8,pts:68,competition:"laliga",emoji:"🔥"},
  {id:310,name:"Juanmi",                 team:"Getafe",         pos:"DEL",val: 6,pts:58,competition:"laliga",emoji:"🔥"},
  {id:311,name:"Martín Satriano",        team:"Getafe",         pos:"DEL",val: 6,pts:58,competition:"laliga",emoji:"🔥"},
  // Celta Vigo
  {id:312,name:"Iván Villar",            team:"Celta Vigo",     pos:"POR",val: 7,pts:65,competition:"laliga",emoji:"🧤"},
  {id:313,name:"Andrei Radu",            team:"Celta Vigo",     pos:"POR",val: 5,pts:52,competition:"laliga",emoji:"🧤"},
  {id:314,name:"Carl Starfelt",          team:"Celta Vigo",     pos:"DEF",val: 7,pts:60,competition:"laliga",emoji:"🛡️"},
  {id:315,name:"Óscar Mingueza",         team:"Celta Vigo",     pos:"DEF",val: 8,pts:65,competition:"laliga",emoji:"🛡️"},
  {id:316,name:"Joseph Aidoo",           team:"Celta Vigo",     pos:"DEF",val: 6,pts:56,competition:"laliga",emoji:"🛡️"},
  {id:317,name:"Marcos Alonso",          team:"Celta Vigo",     pos:"DEF",val: 6,pts:58,competition:"laliga",emoji:"🛡️"},
  {id:318,name:"Mihailo Ristic",         team:"Celta Vigo",     pos:"DEF",val: 5,pts:54,competition:"laliga",emoji:"🛡️"},
  {id:319,name:"Matías Vecino",          team:"Celta Vigo",     pos:"MED",val: 7,pts:60,competition:"laliga",emoji:"⚡"},
  {id:320,name:"Ilaix Moriba",           team:"Celta Vigo",     pos:"MED",val: 7,pts:58,competition:"laliga",emoji:"⚡"},
  {id:321,name:"Williot Swedberg",       team:"Celta Vigo",     pos:"MED",val: 7,pts:60,competition:"laliga",emoji:"⚡"},
  {id:322,name:"Franco Cervi",           team:"Celta Vigo",     pos:"MED",val: 6,pts:56,competition:"laliga",emoji:"⚡"},
  {id:323,name:"Iago Aspas",             team:"Celta Vigo",     pos:"DEL",val: 9,pts:72,competition:"laliga",emoji:"🔥"},
  {id:324,name:"Ferran Jutglà",          team:"Celta Vigo",     pos:"DEL",val: 8,pts:65,competition:"laliga",emoji:"🔥"},
  {id:325,name:"Borja Iglesias",         team:"Celta Vigo",     pos:"DEL",val: 7,pts:62,competition:"laliga",emoji:"🔥"},
  // Real Sociedad
  {id:326,name:"Álex Remiro",            team:"Real Sociedad",  pos:"POR",val: 9,pts:74,competition:"laliga",emoji:"🧤"},
  {id:327,name:"Jon Aramburu",           team:"Real Sociedad",  pos:"DEF",val: 6,pts:58,competition:"laliga",emoji:"🛡️"},
  {id:328,name:"Aihen Muñoz",            team:"Real Sociedad",  pos:"DEF",val: 6,pts:56,competition:"laliga",emoji:"🛡️"},
  {id:329,name:"Igor Zubeldia",          team:"Real Sociedad",  pos:"DEF",val: 7,pts:62,competition:"laliga",emoji:"🛡️"},
  {id:330,name:"Duje Caleta-Car",        team:"Real Sociedad",  pos:"DEF",val: 7,pts:60,competition:"laliga",emoji:"🛡️"},
  {id:331,name:"Álvaro Odriozola",       team:"Real Sociedad",  pos:"DEF",val: 5,pts:52,competition:"laliga",emoji:"🛡️"},
  {id:332,name:"Beñat Turrientes",       team:"Real Sociedad",  pos:"MED",val: 7,pts:62,competition:"laliga",emoji:"⚡"},
  {id:333,name:"Yangel Herrera",         team:"Real Sociedad",  pos:"MED",val: 9,pts:70,competition:"laliga",emoji:"⚡"},
  {id:334,name:"Carlos Soler",           team:"Real Sociedad",  pos:"MED",val: 7,pts:62,competition:"laliga",emoji:"⚡"},
  {id:335,name:"Arsen Zakharyan",        team:"Real Sociedad",  pos:"MED",val: 8,pts:66,competition:"laliga",emoji:"⚡"},
  {id:336,name:"Brais Méndez",           team:"Real Sociedad",  pos:"MED",val: 9,pts:70,competition:"laliga",emoji:"⚡"},
  {id:337,name:"Luka Sucic",             team:"Real Sociedad",  pos:"MED",val: 7,pts:62,competition:"laliga",emoji:"⚡"},
  {id:338,name:"Mikel Oyarzabal",        team:"Real Sociedad",  pos:"DEL",val:12,pts:78,competition:"laliga",emoji:"🔥"},
  {id:339,name:"Takefusa Kubo",          team:"Real Sociedad",  pos:"DEL",val:12,pts:80,competition:"laliga",emoji:"🔥"},
  {id:340,name:"A. Barrenetxea",         team:"Real Sociedad",  pos:"DEL",val: 9,pts:70,competition:"laliga",emoji:"🔥"},
  {id:341,name:"Sergio Gómez",           team:"Real Sociedad",  pos:"DEL",val: 7,pts:60,competition:"laliga",emoji:"🔥"},
  // Athletic Club
  {id:342,name:"Unai Simón",             team:"Athletic Club",  pos:"POR",val:10,pts:76,competition:"laliga",emoji:"🧤"},
  {id:343,name:"A. Gorosabel",           team:"Athletic Club",  pos:"DEF",val: 6,pts:58,competition:"laliga",emoji:"🛡️"},
  {id:344,name:"Dani Vivian",            team:"Athletic Club",  pos:"DEF",val: 8,pts:65,competition:"laliga",emoji:"🛡️"},
  {id:345,name:"Aitor Paredes",          team:"Athletic Club",  pos:"DEF",val: 7,pts:62,competition:"laliga",emoji:"🛡️"},
  {id:346,name:"Yeray",                  team:"Athletic Club",  pos:"DEF",val: 7,pts:62,competition:"laliga",emoji:"🛡️"},
  {id:347,name:"Aymeric Laporte",        team:"Athletic Club",  pos:"DEF",val:10,pts:72,competition:"laliga",emoji:"🛡️"},
  {id:348,name:"Yuri Berchiche",         team:"Athletic Club",  pos:"DEF",val: 6,pts:58,competition:"laliga",emoji:"🛡️"},
  {id:349,name:"Mikel Vesga",            team:"Athletic Club",  pos:"MED",val: 7,pts:60,competition:"laliga",emoji:"⚡"},
  {id:350,name:"Oihan Sancet",           team:"Athletic Club",  pos:"MED",val:10,pts:72,competition:"laliga",emoji:"⚡"},
  {id:351,name:"I. Ruiz de Galarreta",   team:"Athletic Club",  pos:"MED",val: 7,pts:62,competition:"laliga",emoji:"⚡"},
  {id:352,name:"Robert Navarro",         team:"Athletic Club",  pos:"MED",val: 7,pts:62,competition:"laliga",emoji:"⚡"},
  {id:353,name:"Álex Berenguer",         team:"Athletic Club",  pos:"DEL",val: 7,pts:62,competition:"laliga",emoji:"🔥"},
  {id:354,name:"Iñaki Williams",         team:"Athletic Club",  pos:"DEL",val:12,pts:78,competition:"laliga",emoji:"🔥"},
  {id:355,name:"Nico Williams",          team:"Athletic Club",  pos:"DEL",val:16,pts:87,competition:"laliga",emoji:"🔥"},
  {id:356,name:"Gorka Guruzeta",         team:"Athletic Club",  pos:"DEL",val: 9,pts:70,competition:"laliga",emoji:"🔥"},
  // Osasuna
  {id:357,name:"Sergio Herrera",         team:"Osasuna",        pos:"POR",val: 7,pts:64,competition:"laliga",emoji:"🧤"},
  {id:358,name:"Aitor Fernández",        team:"Osasuna",        pos:"POR",val: 6,pts:60,competition:"laliga",emoji:"🧤"},
  {id:359,name:"Juan Cruz",              team:"Osasuna",        pos:"DEF",val: 5,pts:54,competition:"laliga",emoji:"🛡️"},
  {id:360,name:"Javi Galán",             team:"Osasuna",        pos:"DEF",val: 7,pts:62,competition:"laliga",emoji:"🛡️"},
  {id:361,name:"Alejandro Catena",       team:"Osasuna",        pos:"DEF",val: 6,pts:56,competition:"laliga",emoji:"🛡️"},
  {id:362,name:"Jorge Herrando",         team:"Osasuna",        pos:"DEF",val: 5,pts:52,competition:"laliga",emoji:"🛡️"},
  {id:363,name:"Lucas Torró",            team:"Osasuna",        pos:"MED",val: 6,pts:58,competition:"laliga",emoji:"⚡"},
  {id:364,name:"Jon Moncayola",          team:"Osasuna",        pos:"MED",val: 6,pts:58,competition:"laliga",emoji:"⚡"},
  {id:365,name:"Aimar Oroz",             team:"Osasuna",        pos:"MED",val: 7,pts:62,competition:"laliga",emoji:"⚡"},
  {id:366,name:"Rubén García",           team:"Osasuna",        pos:"MED",val: 7,pts:60,competition:"laliga",emoji:"⚡"},
  {id:367,name:"Moi Gómez",              team:"Osasuna",        pos:"MED",val: 6,pts:60,competition:"laliga",emoji:"⚡"},
  {id:368,name:"Ante Budimir",           team:"Osasuna",        pos:"DEL",val: 8,pts:68,competition:"laliga",emoji:"🔥"},
  {id:369,name:"Raúl García",            team:"Osasuna",        pos:"DEL",val: 7,pts:62,competition:"laliga",emoji:"🔥"},
  {id:370,name:"Raúl Moro",              team:"Osasuna",        pos:"DEL",val: 6,pts:58,competition:"laliga",emoji:"🔥"},
  // Rayo Vallecano
  {id:371,name:"Daniel Cárdenas",        team:"Rayo Vallecano", pos:"POR",val: 6,pts:60,competition:"laliga",emoji:"🧤"},
  {id:372,name:"Augusto Batalla",        team:"Rayo Vallecano", pos:"POR",val: 5,pts:52,competition:"laliga",emoji:"🧤"},
  {id:373,name:"Andrei Ratiu",           team:"Rayo Vallecano", pos:"DEF",val: 6,pts:58,competition:"laliga",emoji:"🛡️"},
  {id:374,name:"Pep Chavarría",          team:"Rayo Vallecano", pos:"DEF",val: 5,pts:52,competition:"laliga",emoji:"🛡️"},
  {id:375,name:"Luiz Felipe",            team:"Rayo Vallecano", pos:"DEF",val: 7,pts:60,competition:"laliga",emoji:"🛡️"},
  {id:376,name:"Abdul Mumin",            team:"Rayo Vallecano", pos:"DEF",val: 6,pts:56,competition:"laliga",emoji:"🛡️"},
  {id:377,name:"Iván Balliu",            team:"Rayo Vallecano", pos:"DEF",val: 5,pts:54,competition:"laliga",emoji:"🛡️"},
  {id:378,name:"Pacha Espino",           team:"Rayo Vallecano", pos:"DEF",val: 5,pts:54,competition:"laliga",emoji:"🛡️"},
  {id:379,name:"Pathé Ciss",             team:"Rayo Vallecano", pos:"MED",val: 7,pts:60,competition:"laliga",emoji:"⚡"},
  {id:380,name:"Isi Palazón",            team:"Rayo Vallecano", pos:"MED",val: 8,pts:65,competition:"laliga",emoji:"⚡"},
  {id:381,name:"Óscar Trejo",            team:"Rayo Vallecano", pos:"MED",val: 7,pts:60,competition:"laliga",emoji:"⚡"},
  {id:382,name:"Randy Nteka",            team:"Rayo Vallecano", pos:"MED",val: 6,pts:58,competition:"laliga",emoji:"⚡"},
  {id:383,name:"Álvaro García",          team:"Rayo Vallecano", pos:"MED",val: 7,pts:62,competition:"laliga",emoji:"⚡"},
  {id:384,name:"Sergio Camello",         team:"Rayo Vallecano", pos:"DEL",val: 6,pts:58,competition:"laliga",emoji:"🔥"},
  {id:385,name:"Ilias Akhomach",         team:"Rayo Vallecano", pos:"DEL",val: 6,pts:58,competition:"laliga",emoji:"🔥"},
  {id:386,name:"Jorge de Frutos",        team:"Rayo Vallecano", pos:"DEL",val: 6,pts:56,competition:"laliga",emoji:"🔥"},
  // Espanyol
  {id:387,name:"Marko Dmitrovic",        team:"Espanyol",       pos:"POR",val: 6,pts:60,competition:"laliga",emoji:"🧤"},
  {id:388,name:"Ángel Fortuño",          team:"Espanyol",       pos:"POR",val: 4,pts:50,competition:"laliga",emoji:"🧤"},
  {id:389,name:"Leandro Cabrera",        team:"Espanyol",       pos:"DEF",val: 6,pts:56,competition:"laliga",emoji:"🛡️"},
  {id:390,name:"Fernando Calero",        team:"Espanyol",       pos:"DEF",val: 5,pts:52,competition:"laliga",emoji:"🛡️"},
  {id:391,name:"Rubén Sánchez",          team:"Espanyol",       pos:"DEF",val: 5,pts:52,competition:"laliga",emoji:"🛡️"},
  {id:392,name:"Edu Expósito",           team:"Espanyol",       pos:"MED",val: 6,pts:58,competition:"laliga",emoji:"⚡"},
  {id:393,name:"Ramón Terrats",          team:"Espanyol",       pos:"MED",val: 5,pts:54,competition:"laliga",emoji:"⚡"},
  {id:394,name:"Charles Pickel",         team:"Espanyol",       pos:"MED",val: 5,pts:54,competition:"laliga",emoji:"⚡"},
  {id:395,name:"Pere Milla",             team:"Espanyol",       pos:"MED",val: 5,pts:54,competition:"laliga",emoji:"⚡"},
  {id:396,name:"Javier Puado",           team:"Espanyol",       pos:"DEL",val: 6,pts:58,competition:"laliga",emoji:"🔥"},
  {id:397,name:"Cyril Ngonge",           team:"Espanyol",       pos:"DEL",val: 6,pts:58,competition:"laliga",emoji:"🔥"},
  // Girona
  {id:398,name:"Paulo Gazzaniga",        team:"Girona",         pos:"POR",val: 7,pts:64,competition:"laliga",emoji:"🧤"},
  {id:399,name:"Juan Carlos",            team:"Girona",         pos:"POR",val: 5,pts:55,competition:"laliga",emoji:"🧤"},
  {id:400,name:"Arnau Martínez",         team:"Girona",         pos:"DEF",val: 8,pts:65,competition:"laliga",emoji:"🛡️"},
  {id:401,name:"David López",            team:"Girona",         pos:"DEF",val: 6,pts:58,competition:"laliga",emoji:"🛡️"},
  {id:402,name:"Daley Blind",            team:"Girona",         pos:"DEF",val: 6,pts:58,competition:"laliga",emoji:"🛡️"},
  {id:403,name:"Axel Witsel",            team:"Girona",         pos:"DEF",val: 6,pts:56,competition:"laliga",emoji:"🛡️"},
  {id:404,name:"Álex Moreno",            team:"Girona",         pos:"DEF",val: 7,pts:60,competition:"laliga",emoji:"🛡️"},
  {id:405,name:"Fran Beltrán",           team:"Girona",         pos:"MED",val: 7,pts:62,competition:"laliga",emoji:"⚡"},
  {id:406,name:"Thomas Lemar",           team:"Girona",         pos:"MED",val: 7,pts:62,competition:"laliga",emoji:"⚡"},
  {id:407,name:"Claudio Echeverri",      team:"Girona",         pos:"MED",val: 8,pts:64,competition:"laliga",emoji:"⚡"},
  {id:408,name:"Iván Martín",            team:"Girona",         pos:"MED",val: 7,pts:62,competition:"laliga",emoji:"⚡"},
  {id:409,name:"Abel Ruiz",              team:"Girona",         pos:"DEL",val: 8,pts:65,competition:"laliga",emoji:"🔥"},
  {id:410,name:"Cristhian Stuani",       team:"Girona",         pos:"DEL",val: 7,pts:62,competition:"laliga",emoji:"🔥"},
  {id:411,name:"Viktor Tsygankov",       team:"Girona",         pos:"DEL",val: 7,pts:62,competition:"laliga",emoji:"🔥"},
  {id:412,name:"Bryan Gil",              team:"Girona",         pos:"DEL",val: 7,pts:62,competition:"laliga",emoji:"🔥"},
  // Valencia
  {id:413,name:"S. Dimitrievski",        team:"Valencia",       pos:"POR",val: 6,pts:60,competition:"laliga",emoji:"🧤"},
  {id:414,name:"Mouctar Diakhaby",       team:"Valencia",       pos:"DEF",val: 6,pts:56,competition:"laliga",emoji:"🛡️"},
  {id:415,name:"César Tárrega",          team:"Valencia",       pos:"DEF",val: 7,pts:60,competition:"laliga",emoji:"🛡️"},
  {id:416,name:"Javier Guerra",          team:"Valencia",       pos:"DEF",val: 6,pts:56,competition:"laliga",emoji:"🛡️"},
  {id:417,name:"Thierry Correia",        team:"Valencia",       pos:"DEF",val: 6,pts:56,competition:"laliga",emoji:"🛡️"},
  {id:418,name:"José Gayà",              team:"Valencia",       pos:"DEF",val: 7,pts:62,competition:"laliga",emoji:"🛡️"},
  {id:419,name:"Guido Rodríguez",        team:"Valencia",       pos:"MED",val: 7,pts:62,competition:"laliga",emoji:"⚡"},
  {id:420,name:"Pepelu",                 team:"Valencia",       pos:"MED",val: 7,pts:60,competition:"laliga",emoji:"⚡"},
  {id:421,name:"André Almeida",          team:"Valencia",       pos:"MED",val: 6,pts:56,competition:"laliga",emoji:"⚡"},
  {id:422,name:"Hugo Duro",              team:"Valencia",       pos:"DEL",val: 8,pts:65,competition:"laliga",emoji:"🔥"},
  {id:423,name:"Luis Rioja",             team:"Valencia",       pos:"DEL",val: 6,pts:58,competition:"laliga",emoji:"🔥"},
  {id:424,name:"Arnaut Danjuma",         team:"Valencia",       pos:"DEL",val: 7,pts:60,competition:"laliga",emoji:"🔥"},
  // Mallorca
  {id:425,name:"Leo Román",              team:"Mallorca",       pos:"POR",val: 7,pts:65,competition:"laliga",emoji:"🧤"},
  {id:426,name:"Iván Cuéllar",           team:"Mallorca",       pos:"POR",val: 5,pts:52,competition:"laliga",emoji:"🧤"},
  {id:427,name:"Antonio Raíllo",         team:"Mallorca",       pos:"DEF",val: 6,pts:58,competition:"laliga",emoji:"🛡️"},
  {id:428,name:"Pablo Maffeo",           team:"Mallorca",       pos:"DEF",val: 7,pts:62,competition:"laliga",emoji:"🛡️"},
  {id:429,name:"Johan Mojica",           team:"Mallorca",       pos:"DEF",val: 6,pts:58,competition:"laliga",emoji:"🛡️"},
  {id:430,name:"Martin Valjent",         team:"Mallorca",       pos:"DEF",val: 6,pts:56,competition:"laliga",emoji:"🛡️"},
  {id:431,name:"Toni Lato",              team:"Mallorca",       pos:"DEF",val: 6,pts:56,competition:"laliga",emoji:"🛡️"},
  {id:432,name:"Sergi Darder",           team:"Mallorca",       pos:"MED",val: 7,pts:62,competition:"laliga",emoji:"⚡"},
  {id:433,name:"Antonio Sánchez",        team:"Mallorca",       pos:"MED",val: 6,pts:58,competition:"laliga",emoji:"⚡"},
  {id:434,name:"Samú Costa",             team:"Mallorca",       pos:"MED",val: 6,pts:58,competition:"laliga",emoji:"⚡"},
  {id:435,name:"Pablo Torre",            team:"Mallorca",       pos:"MED",val: 8,pts:65,competition:"laliga",emoji:"⚡"},
  {id:436,name:"Vedat Muriqi",           team:"Mallorca",       pos:"DEL",val: 9,pts:70,competition:"laliga",emoji:"🔥"},
  {id:437,name:"Abdón Prats",            team:"Mallorca",       pos:"DEL",val: 6,pts:58,competition:"laliga",emoji:"🔥"},
  {id:438,name:"Takuma Asano",           team:"Mallorca",       pos:"DEL",val: 7,pts:62,competition:"laliga",emoji:"🔥"},
  {id:439,name:"Zito Luvumbo",           team:"Mallorca",       pos:"DEL",val: 7,pts:62,competition:"laliga",emoji:"🔥"},
  // Elche
  {id:440,name:"Iñaki Peña",             team:"Elche",          pos:"POR",val: 6,pts:58,competition:"laliga",emoji:"🧤"},
  {id:441,name:"Matías Dituro",          team:"Elche",          pos:"POR",val: 5,pts:52,competition:"laliga",emoji:"🧤"},
  {id:442,name:"Adrià Pedrosa",          team:"Elche",          pos:"DEF",val: 6,pts:56,competition:"laliga",emoji:"🛡️"},
  {id:443,name:"Pedro Bigas",            team:"Elche",          pos:"DEF",val: 5,pts:52,competition:"laliga",emoji:"🛡️"},
  {id:444,name:"Léo Pétrot",             team:"Elche",          pos:"DEF",val: 5,pts:52,competition:"laliga",emoji:"🛡️"},
  {id:445,name:"Víctor Chust",           team:"Elche",          pos:"DEF",val: 5,pts:52,competition:"laliga",emoji:"🛡️"},
  {id:446,name:"Federico Redondo",       team:"Elche",          pos:"MED",val: 6,pts:58,competition:"laliga",emoji:"⚡"},
  {id:447,name:"Marc Aguado",            team:"Elche",          pos:"MED",val: 5,pts:52,competition:"laliga",emoji:"⚡"},
  {id:448,name:"Gonzalo Villar",         team:"Elche",          pos:"MED",val: 6,pts:58,competition:"laliga",emoji:"⚡"},
  {id:449,name:"Aleix Febas",            team:"Elche",          pos:"MED",val: 5,pts:54,competition:"laliga",emoji:"⚡"},
  {id:450,name:"André Silva",            team:"Elche",          pos:"DEL",val: 8,pts:65,competition:"laliga",emoji:"🔥"},
  {id:451,name:"Rafa Mir",               team:"Elche",          pos:"DEL",val: 7,pts:60,competition:"laliga",emoji:"🔥"},
  {id:452,name:"Germán Valera",          team:"Elche",          pos:"DEL",val: 6,pts:56,competition:"laliga",emoji:"🔥"},
  // Sevilla
  {id:453,name:"O. Vlachodimos",         team:"Sevilla",        pos:"POR",val: 7,pts:65,competition:"laliga",emoji:"🧤"},
  {id:454,name:"Ørjan Nyland",           team:"Sevilla",        pos:"POR",val: 5,pts:55,competition:"laliga",emoji:"🧤"},
  {id:455,name:"J.Á. Carmona",           team:"Sevilla",        pos:"DEF",val: 7,pts:60,competition:"laliga",emoji:"🛡️"},
  {id:456,name:"C. Azpilicueta",         team:"Sevilla",        pos:"DEF",val: 7,pts:60,competition:"laliga",emoji:"🛡️"},
  {id:457,name:"Tanguy Nianzou",         team:"Sevilla",        pos:"DEF",val: 7,pts:58,competition:"laliga",emoji:"🛡️"},
  {id:458,name:"Gabriel Suazo",          team:"Sevilla",        pos:"DEF",val: 6,pts:56,competition:"laliga",emoji:"🛡️"},
  {id:459,name:"Fábio Cardoso",          team:"Sevilla",        pos:"DEF",val: 5,pts:52,competition:"laliga",emoji:"🛡️"},
  {id:460,name:"Nemanja Gudelj",         team:"Sevilla",        pos:"MED",val: 7,pts:62,competition:"laliga",emoji:"⚡"},
  {id:461,name:"Joan Jordán",            team:"Sevilla",        pos:"MED",val: 7,pts:60,competition:"laliga",emoji:"⚡"},
  {id:462,name:"Juanlu Sanchez",         team:"Sevilla",        pos:"MED",val: 7,pts:60,competition:"laliga",emoji:"⚡"},
  {id:463,name:"Djibril Sow",            team:"Sevilla",        pos:"MED",val: 7,pts:60,competition:"laliga",emoji:"⚡"},
  {id:464,name:"Rubén Vargas",           team:"Sevilla",        pos:"MED",val: 7,pts:60,competition:"laliga",emoji:"⚡"},
  {id:465,name:"Isaac Romero",           team:"Sevilla",        pos:"DEL",val: 8,pts:65,competition:"laliga",emoji:"🔥"},
  {id:466,name:"Alexis Sánchez",         team:"Sevilla",        pos:"DEL",val: 8,pts:66,competition:"laliga",emoji:"🔥"},
  {id:467,name:"Neal Maupay",            team:"Sevilla",        pos:"DEL",val: 6,pts:56,competition:"laliga",emoji:"🔥"},
  // Alavés
  {id:468,name:"Antonio Sivera",         team:"Alavés",         pos:"POR",val: 6,pts:62,competition:"laliga",emoji:"🧤"},
  {id:469,name:"Facundo Garcés",         team:"Alavés",         pos:"DEF",val: 6,pts:56,competition:"laliga",emoji:"🛡️"},
  {id:470,name:"Jon Pacheco",            team:"Alavés",         pos:"DEF",val: 5,pts:52,competition:"laliga",emoji:"🛡️"},
  {id:471,name:"Nahuel Tenaglia",        team:"Alavés",         pos:"DEF",val: 5,pts:52,competition:"laliga",emoji:"🛡️"},
  {id:472,name:"Jonny",                  team:"Alavés",         pos:"DEF",val: 5,pts:52,competition:"laliga",emoji:"🛡️"},
  {id:473,name:"Denis Suárez",           team:"Alavés",         pos:"MED",val: 6,pts:58,competition:"laliga",emoji:"⚡"},
  {id:474,name:"Ander Guevara",          team:"Alavés",         pos:"MED",val: 6,pts:58,competition:"laliga",emoji:"⚡"},
  {id:475,name:"Antonio Blanco",         team:"Alavés",         pos:"MED",val: 5,pts:52,competition:"laliga",emoji:"⚡"},
  {id:476,name:"Carles Aleñá",           team:"Alavés",         pos:"MED",val: 5,pts:52,competition:"laliga",emoji:"⚡"},
  {id:477,name:"Toni Martínez",          team:"Alavés",         pos:"DEL",val: 6,pts:58,competition:"laliga",emoji:"🔥"},
  {id:478,name:"Lucas Boyé",             team:"Alavés",         pos:"DEL",val: 6,pts:58,competition:"laliga",emoji:"🔥"},
  {id:479,name:"Abde Rebbach",           team:"Alavés",         pos:"DEL",val: 5,pts:52,competition:"laliga",emoji:"🔥"},
  // Levante
  {id:480,name:"Mathew Ryan",            team:"Levante",        pos:"POR",val: 6,pts:60,competition:"laliga",emoji:"🧤"},
  {id:481,name:"Manu Sánchez",           team:"Levante",        pos:"DEF",val: 5,pts:52,competition:"laliga",emoji:"🛡️"},
  {id:482,name:"Alan Matturro",          team:"Levante",        pos:"DEF",val: 5,pts:52,competition:"laliga",emoji:"🛡️"},
  {id:483,name:"Jeremy Toljan",          team:"Levante",        pos:"DEF",val: 5,pts:52,competition:"laliga",emoji:"🛡️"},
  {id:484,name:"Unai Vencedor",          team:"Levante",        pos:"MED",val: 6,pts:58,competition:"laliga",emoji:"⚡"},
  {id:485,name:"Kervin Arriaga",         team:"Levante",        pos:"MED",val: 5,pts:54,competition:"laliga",emoji:"⚡"},
  {id:486,name:"J.L. Morales",           team:"Levante",        pos:"DEL",val: 6,pts:58,competition:"laliga",emoji:"🔥"},
  {id:487,name:"Iván Romero",            team:"Levante",        pos:"DEL",val: 5,pts:52,competition:"laliga",emoji:"🔥"},
  // Real Oviedo
  {id:488,name:"Horatiu Moldovan",       team:"Real Oviedo",    pos:"POR",val: 6,pts:60,competition:"laliga",emoji:"🧤"},
  {id:489,name:"Aarón Escandell",        team:"Real Oviedo",    pos:"POR",val: 5,pts:52,competition:"laliga",emoji:"🧤"},
  {id:490,name:"Eric Bailly",            team:"Real Oviedo",    pos:"DEF",val: 6,pts:56,competition:"laliga",emoji:"🛡️"},
  {id:491,name:"David Carmo",            team:"Real Oviedo",    pos:"DEF",val: 5,pts:52,competition:"laliga",emoji:"🛡️"},
  {id:492,name:"David Costas",           team:"Real Oviedo",    pos:"DEF",val: 5,pts:52,competition:"laliga",emoji:"🛡️"},
  {id:493,name:"Nacho Vidal",            team:"Real Oviedo",    pos:"DEF",val: 5,pts:52,competition:"laliga",emoji:"🛡️"},
  {id:494,name:"Santi Cazorla",          team:"Real Oviedo",    pos:"MED",val: 6,pts:60,competition:"laliga",emoji:"⚡"},
  {id:495,name:"L. Dendoncker",          team:"Real Oviedo",    pos:"MED",val: 6,pts:56,competition:"laliga",emoji:"⚡"},
  {id:496,name:"Luka Ilic",              team:"Real Oviedo",    pos:"MED",val: 6,pts:56,competition:"laliga",emoji:"⚡"},
  {id:497,name:"Nicolás Fonseca",        team:"Real Oviedo",    pos:"MED",val: 5,pts:52,competition:"laliga",emoji:"⚡"},
  {id:498,name:"Ilyas Chaira",           team:"Real Oviedo",    pos:"DEL",val: 5,pts:52,competition:"laliga",emoji:"🔥"},
  {id:499,name:"Federico Viñas",         team:"Real Oviedo",    pos:"DEL",val: 5,pts:52,competition:"laliga",emoji:"🔥"},
  {id:500,name:"Haissem Hassan",         team:"Real Oviedo",    pos:"DEL",val: 5,pts:52,competition:"laliga",emoji:"🔥"},
];

export function getPlayer(id) {
  return PLAYERS.find(p => p.id === id);
}

export function getByCompetition(competition) {
  return PLAYERS.filter(p => p.competition === competition);
}
